# Generated by Django 2.2.16 on 2020-10-29 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='歌手')),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan', models.CharField(max_length=10, verbose_name='音階名(日本式)')),
                ('universal', models.CharField(max_length=10, verbose_name='音階名(国際表記)')),
            ],
            options={
                'db_table': 'scale',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karaoke.Artist', verbose_name='歌手')),
                ('heighest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heighest_scale', to='karaoke.Scale', verbose_name='最高音')),
                ('lowest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lowest_scale', to='karaoke.Scale', verbose_name='最低音')),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
