# Generated by Django 2.2.16 on 2020-11-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='歌手')),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan', models.CharField(max_length=10, verbose_name='音階名(日本式)')),
                ('universal', models.CharField(max_length=10, verbose_name='音階名(国際表記)')),
            ],
            options={
                'db_table': 'scale',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'voice',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karaoke.Artist', verbose_name='歌手')),
                ('u_highest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_highest', to='karaoke.Scale', verbose_name='裏声最高音')),
                ('u_lowest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_lowest', to='karaoke.Scale', verbose_name='裏声最低音')),
                ('z_highest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='z_highest', to='karaoke.Scale', verbose_name='地声最高音')),
                ('z_lowest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='z_lowest', to='karaoke.Scale', verbose_name='地声最低音')),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
