# Generated by Django 2.2.16 on 2020-12-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_highest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_u_highest', to='karaoke.Scale', verbose_name='裏声最高音')),
                ('u_lowest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_u_lowest', to='karaoke.Scale', verbose_name='裏声最低音')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('z_highest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_z_highest', to='karaoke.Scale', verbose_name='地声最高音')),
                ('z_lowest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_z_lowest', to='karaoke.Scale', verbose_name='地声最低音')),
            ],
            options={
                'db_table': 'user_voice',
            },
        ),
    ]
