# Generated by Django 2.2.16 on 2020-11-05 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='u_heighest',
        ),
        migrations.RemoveField(
            model_name='song',
            name='z_heighest',
        ),
        migrations.AddField(
            model_name='song',
            name='u_highest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_highest', to='karaoke.Scale', verbose_name='裏声最高音'),
        ),
        migrations.AddField(
            model_name='song',
            name='z_highest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='z_highest', to='karaoke.Scale', verbose_name='地声最高音'),
        ),
    ]
