# Generated by Django 2.2.16 on 2020-11-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_auto_20201105_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'voice',
            },
        ),
    ]
