# Generated by Django 2.2.16 on 2020-12-07 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karaoke', '0002_uservoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVoice',
            new_name='UserScale',
        ),
        migrations.AlterModelTable(
            name='userscale',
            table='user_scale',
        ),
    ]
